apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dockerpoc
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/Helm
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 30s
