# dockerpoc-chart/templates/deployment.yaml
apiVersion: {{ include "dockerpoc-chart.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: dockerpoc-1
  labels:
    {{- include "dockerpoc-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dockerpoc-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dockerpoc-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dockerpoc-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
            - name: debug
              containerPort: {{ .Values.containerPorts.debug }}
          env:
            - name: env_value
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecret.name }}
                  key: SECRET-VALUE # This key is fixed from your original secret
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: filestorage
              mountPath: /opt/file
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: filestorage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.pvcName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}