apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dockerpoc-app.fullname" . }}   # -> dockerpoc-1 via fullnameOverride
  labels:
    app.kubernetes.io/name: {{ include "dockerpoc-app.name" . }}
    {{- include "dockerpoc-app.deploymentComponentLabel" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dockerpoc-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dockerpoc-app.name" . }}
    spec:
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: {{ include "dockerpoc-app.image" . }}
          imagePullPolicy: {{ .Values.deployment.container.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.container.ports.http }}
            - name: debug
              containerPort: {{ .Values.deployment.container.ports.debug }}
          env:
            - name: env_value
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.deployment.container.envFromSecretKey.secretName }}
                  key: {{ .Values.deployment.container.envFromSecretKey.key }}
          volumeMounts:
            - name: {{ .Values.persistence.volumeName }}
              mountPath: {{ .Values.persistence.mountPath }}
          resources:
            {{- toYaml .Values.deployment.container.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.persistence.volumeName }}
          persistentVolumeClaim:
            claimName: {{ include "dockerpoc-app.pvcName" . }}
