# dockerpoc-chart/templates/ingress.yaml
{{ if .Values.ingress.enabled -}}
apiVersion: {{ include "dockerpoc-chart.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "dockerpoc-chart.fullname" . }}
  labels:
    {{- include "dockerpoc-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and (.Values.ingress.className) (semverCompare "<1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  # Ingress class annotation is deprecated in K8s 1.18+
  # Use ingressClassName field instead for K8s 1.18+
    {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- end }}
    {{- else if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
    {{- end }}
    {{- if .Values.ingress.tls }}
  tls:
      {{- range .Values.ingress.tls }}
    - hosts:
          {{- range .hosts }}
        - {{ . | quote }}
          {{- end }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  rules:
    - http: # Make 'rules' an array with a single rule item
        paths:
        {{- range .Values.ingress.paths }} # Correctly iterate over paths from values.yaml
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.serviceName }} # .backend is from the path item in values
                port:
                    {{- if .backend.servicePortName }}
                  name: {{ .backend.servicePortName }}
                    {{- else if .backend.servicePort }}
                  number: {{ .backend.servicePort }}
                    {{- else }}
                  # Default or error if neither is provided
                  name: http # Sensible default
                    {{- end }}
            {{- end }} # End of .Values.ingress.paths loop
  {{- /* The extraneous {{- end }} was removed from here */}}
{{- end }}