{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dockerpoc-app.ingressName" . }}
  labels:
    {{- include "dockerpoc-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}

  # Hostless rules (what you’re using)
  rules:
    {{- range $r := .Values.ingress.rules }}
    - http:
        paths:
          {{- range $p := $r.paths }}
          - path: {{ $p.path }}
            pathType: {{ $p.pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ $p.backend.service.name }}
                {{- if $p.backend.service.port.name }}
                port: { name: {{ $p.backend.service.port.name }} }
                {{- else }}
                port: { number: {{ $p.backend.service.port.number }} }
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
