{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dockerpoc-app.fullname" . }}
  labels:
    {{- include "dockerpoc-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: security
  {{- with .Values.networkPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "dockerpoc-app.selectorLabels" . | nindent 6 }}

  policyTypes:
    {{- if .Values.networkPolicy.ingress }}- Ingress{{- end }}
    {{- if .Values.networkPolicy.egress  }}- Egress {{- end }}

  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- if .Values.networkPolicy.ingress.rules }}
    {{- toYaml .Values.networkPolicy.ingress.rules | nindent 4 }}
    {{- else }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.containerPorts.http }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.containerPorts.http }}
    {{- end }}
  {{- end }}

  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- if .Values.networkPolicy.egress.rules }}
    {{- toYaml .Values.networkPolicy.egress.rules | nindent 4 }}
    {{- else }}
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to: []
      ports:
        - protocol: TCP
          port: 443
    - to: []
      ports:
        - protocol: TCP
          port: 80
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
