# dockerpoc-chart/templates/persistentvolume.yaml
  {{- if and .Values.persistence.enabled .Values.persistence.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pv.name }}
  labels:
    {{- include "dockerpoc-chart.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }} # Should match the SC or PVC's SC
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  hostPath:
    path: {{ .Values.persistence.pv.hostPath }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.pv.reclaimPolicy }}
  {{- end }}