{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dockerpoc-app.pvcName" . }}     # file-pvc
  labels:
    app.kubernetes.io/name: {{ include "dockerpoc-app.name" . }}
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 2 }}
  storageClassName: {{ include "dockerpoc-app.storageClassName" . }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
