{{- if and .Values.persistence.enabled .Values.persistence.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "dockerpoc-app.pvName" . }}      # pv-volume
spec:
  storageClassName: {{ .Values.persistence.pv.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.pv.size }}
  accessModes:
    {{- toYaml .Values.persistence.pv.accessModes | nindent 2 }}
  {{- if .Values.persistence.pv.hostPath.enabled }}
  hostPath:
    path: {{ .Values.persistence.pv.hostPath.path | quote }}
  {{- end }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.pv.reclaimPolicy }}
{{- end }}
