{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}   # env-secret
type: {{ .Values.secret.type }}
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
