apiVersion: v1
kind: Service
metadata:
  name: dockerpoc-1
  labels:
    app.kubernetes.io/name: dockerpoc-1
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPortName }}
      name: http
  selector:
    {{- include "dockerpoc-chart.selectorLabels" . | nindent 4 }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dockerpoc-1
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /ingress/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dockerpoc-1
                port:
                  name: http
          - path: /cloud/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cloudtest
                port:
                  number: 9015