# dockerpoc-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dockerpoc-1
  labels:
    app.kubernetes.io/name: dockerpoc-1
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPortName }}
      name: http
  selector:
    {{- include "dockerpoc-chart.selectorLabels" . | nindent 4 }}
---
  {{- if .Values.nodePortService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dockerpoc-chart.fullname" . }}{{ .Values.nodePortService.nameSuffix }}
  labels:
    {{- include "dockerpoc-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.nodePortService.port }}
      targetPort: {{ .Values.nodePortService.targetPortName }}
      nodePort: {{ .Values.nodePortService.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "dockerpoc-chart.selectorLabels" . | nindent 4 }}
  {{- end }}