apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dockerpoc-1
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /ingress/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dockerpoc-1
                port:
                  name: http
          - path: /cloud/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cloudtest
                port:
                  number: 9015