# DEPLOYMENT.YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerpoc-1-deployment
  labels:
    canbeanykey: canbeanyvalue
spec:
  replicas: 2
  selector:
    matchLabels:
      component: dockerpoc-1
  template:
    metadata:
      labels:
        component: dockerpoc-1
    spec:
      containers:
        - name: dockerpoc-1
          image: vishal210893/dockerpoc-1:7
          ports:
            - containerPort: 8005
          env:
            - name: env_value
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: SECRET-VALUE
          volumeMounts:
            - mountPath: /opt/file
              name: filestorage
      volumes:
        - name: filestorage
          persistentVolumeClaim:
            claimName: file-pvc

---

# CLUSTER-IP.YAML
apiVersion: v1
kind: Service
metadata:
  name: dockerpoc-1-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: dockerpoc-1
  ports:
    - port: 8005
      targetPort: 8005

---

# STORAGE CLASS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dockerpoc-sc
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd

---

# PV.YAML
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
spec:
  storageClassName: dockerpoc-sc
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/mount
  persistentVolumeReclaimPolicy: Retain

---

# PVC.YAML
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: dockerpoc-sc
  resources:
    requests:
      storage: 1Gi

---

# SECRET.YAML
apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: generic
stringData:
  SECRET-VALUE: minikube node from secret

---

# INGRESS.YAML
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /dockerpoc1
            pathType: Prefix
            backend:
              service:
                name: dockerpoc-1-cluster-ip
                port:
                  number: 8005
          - path: /cloudtest
            pathType: Prefix
            backend:
              service:
                name: cloudtest-cluster-ip
                port:
                  number: 9015

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-and-pod-logs-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "dave" to read secrets in the "development" namespace.
# You need to already have a ClusterRole named "secret-reader".
kind: RoleBinding
metadata:
  name: read-pod
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "development" namespace.
  namespace: default
subjects:
  - kind: ServiceAccount
    name: my-serviceaccount
    namespace: default
roleRef:
  kind: Role
  name: pod-and-pod-logs-reader
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-serviceaccount
  namespace: default

---

## NODEPORT.YAML
#apiVersion: v1
#kind: Service
#metadata:
#  name: dockerpoc-1-node-port
#spec:
#  type: NodePort
#  ports:
#    - port: 8006
#      targetPort: 8005
#      nodePort: 30555
#  selector:
#    component: dockerpoc-1
