version: '3.4'
services:
  redis-server:
    image: redis
    container_name: redis-cache
    command: redis-server --requirepass "rediscache"
    ports:
    - 6378:6379
    restart: always
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    image: ubuntu/nginx:1
    container_name: nginx-server
    ports:
      - 3050:80
  image-poc:
    build:
      # context: . (. specify current working directory)
      context: .
      # To specify location of dockerfile
      dockerfile: dockerfile
    image: ubuntu/imagepoc:1
    container_name: imagepoc
    volumes:
    - /home/vishal/Desktop/dockermount:/opt/file
    ports:
      - 5000:8005
    environment:
      env_value: Server 1
    restart: always
  devops:
    build:
      context: /home/vishal/Documents/workspace-spring-tool-suite-4-4.3.1.RELEASE/kubernetes/Devops-rest-api
      dockerfile: Dockerfile
    image: ubuntu/devops:1
    container_name: devops
    #ports:
    #  - 5001:8006
    environment:
      env_value: Server 2
    # We can specify starting command in docker-compose also instead of in dockerfile
    entrypoint: [ "sh", "-c", "java -jar /opt/aims/devops.jar"]
    restart: always