version: '3.4'
services:
  redis-server:
    image: redis
    container_name: redis_cache
    command: redis-server --requirepass "rediscache"
    ports:
    - 6378:6379
    restart: always
  image-poc:
    build:
      # context: . (. specify current working directory)
      context: .
      # To specify location of dockerfile
      dockerfile: dockerfile
    image: ubuntu/imagepoc:1
    container_name: imagepoc
    volumes:
    - /home/vishal/Desktop/dockermount:/opt/file
    ports:
      - 5000:8005
    environment:
      imagepoc_env_value: from docker
    restart: always