spring:
  application:
    name: DockerPoc
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:employeedb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always

server:
  port: 8005
  ssl:
    enabled: false
  tomcat:
    max-connections: 50
    connection-timeout: 10s
    threads:
      max: 50
  servlet:
    context-path: /dockerpoc

logging:
  level:
    root: info
