# dockerpoc-chart/templates/storageclass.yaml
  {{- if .Values.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "dockerpoc-chart.labels" . | nindent 4 }}
provisioner: {{ .Values.storageClass.provisioner }}
  {{- with .Values.storageClass.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
  {{- end }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
  {{- if .Values.storageClass.allowVolumeExpansion }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
  {{- end }}
  {{- end }}