apiVersion: v1
kind: ConfigMap
metadata:
  name: testcm
data:
  index.html: "<h1>Hello World</h1>"
  data.html: "Hi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testcmdep
  name: testcmdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcmdep
  strategy: { }
  template:
    metadata:
      labels:
        app: testcmdep
    spec:
      containers:
        - image: yogeshraheja/devopsinaction:v1
          name: devopsinaction
          volumeMounts:
            - name: cmdemo
              mountPath: /var/www/html/
      volumes:
        - name: cmdemo
          configMap:
            name: testcm

---
apiVersion: v1
kind: Service
metadata:
  name: testcmdepsvc
spec:
  type: NodePort
  selector:
    app: testcmdep
  ports:
    - name: 80-80
      port: 80
      targetPort: 80
      nodePort: 30010
      protocol: TCP
