apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: projectedvol
  name: projectedvol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectedvol
  template:
    metadata:
      labels:
        app: projectedvol
    spec:
      containers:
        - image: ubuntu:latest
          name: ubuntu
          command:
            - "sleep"
            - "3600"
          volumeMounts:
            - name: allinone
              mountPath: /projectedvolume
      volumes:
        - name: allinone
          projected:
            sources:
              - secret:
                  name: projectedsecret
                  items:
                    - key: password
                      path: authentication/password
              - configMap:
                  name: projectedcm
                  items:
                    - key: username
                      path: authentication/myuser

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: projectedcm
data:
  username: "test"

---
apiVersion: v1
kind: Secret
metadata:
  name: projectedsecret
data:
  password: cGFzc3dvcmQxMjM=  # Base64 encoded content of password.txt
  username: YWRtaW4=         # Base64 encoded content of username.txt
type: Opaque
