apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsvolpvc
  labels:
    storage: nfsstorage
spec:
  storageClassName: nfsvolstorage
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      storage: nfsstorage
  resources:
    requests:
      storage: 100Mi