apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:8.0.3
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "demopassword"
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - "demors0"
          volumeMounts:
            - name: mongo-vol
              mountPath: /data/db
  serviceName: mongosvc
  volumeClaimTemplates:
    - metadata:
        name: mongo-vol
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: nfsvolstorage
        resources:
          requests:
            storage: 100Mi

---
# HEADLESS SERVICE
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None

---
# STORAGE CLASS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfsvolstorage
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd

---
# PV 1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopv1
  labels:
    storage: nfsstorage
spec:
  storageClassName: nfsvolstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /Users/viskumar/mountpath
  persistentVolumeReclaimPolicy: Delete

---
# PV 2
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopv2
  labels:
    storage: nfsstorage
spec:
  storageClassName: nfsvolstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /Users/viskumar/mountpath
  persistentVolumeReclaimPolicy: Delete

# MONGO CLIENT
# kc run -it --rm --image=mongo:8.0 mongoclient --restart=Never -- mongosh mongodb://mongo-0.mongosvc.default.svc.cluster.local:27017