# SPRING PROPERTIES
spring:
  output:
    ansi:
      enabled: always
  redis:
    host: redis-server
    port: 6379
    password: rediscache

server:
  port: 8005
  ssl:
    enabled: false
  tomcat:
    max-connections: 50
    connection-timeout: 10s
    threads:
      max: 50
  servlet:
    context-path: /dockerpoc1




