apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
        - name: myjob
          image: python:latest
          command: [ "python", "-c" ]
          args: [ "print('Hello from the Kubernetes job')" ]
      restartPolicy: Never
  backoffLimit: 4
  