apiVersion: v2
name: dockerpoc-app
description: Production-grade Helm chart for DockerPoc application
type: application

# Bump when chart structure/templates change (NOT app version).
version: 1.1.0

# Application (container) version. Prefer immutable image tags.
appVersion: "2025.07.23"

# Require a minimum Helm/K8s for features used in templates.
kubeVersion: ">=1.23.0-0"

maintainers:
  - name: Vishal Kumar
    email: vishal210893@gmail.com
    url: https://github.com/vishal210893

keywords:
  - dockerpoc
  - web-application
  - microservice

home: https://github.com/vishal210893/dockerpoc
sources:
  - https://github.com/vishal210893/dockerpoc

annotations:
  category: Application
  licenses: Apache-2.0
  artifacthub.io/changes: |
    - feat: add values.schema.json and new operational templates (HPA, PDB, etc.)
    - chore: enforce stricter labels & security contexts
    - docs: extensive in-template comments
