# dockerpoc-chart/Chart.yaml
apiVersion: v2
name: dockerpoc-chart
description: A Helm chart for deploying the DockerPoc application
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates.
version: 0.5.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "1.0.1"

maintainers:
  - name: Vishal Kumar
    email: vishal210893@gmail.com