name: Build and Deploy

on:
  push:
    branches:
      - learning/github-action

env:
  USER: vishal210893

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache the local Maven repository to speed up builds
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project using Maven
      - name: Maven build
        run: mvn -q install

      # Step 5: Upload the built JAR as an artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/dockerpoc-1.jar

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-artifact
    outputs:
      docker_image: ${{ steps.generate_tag.outputs.docker_image_output }}
    env:
      REPO_NAME: dockerpoc-1
      DOWNLOAD_IMAGE: false
    steps:
      # Step 6: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 7: Download the built JAR artifact
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target

      # Step 8: Generate image tag (single source of truth)
      - name: Generate image tag
        id: generate_tag
        run: |
          IMAGE_TAG="$(date +%Y%m%d-%H%M%S)"
          DOCKER_IMAGE="${USER}/${REPO_NAME}:${IMAGE_TAG}"

          echo "docker_image_output=$DOCKER_IMAGE" >> $GITHUB_OUTPUT
          echo "DOCKER_IMAGE_ENV=$DOCKER_IMAGE" >> $GITHUB_ENV
          echo "GHCR_IMAGE=${REPO_NAME}:${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Debug generated outputs
        run: |
          echo "→ step DOCKER_IMAGE: ${{ steps.generate_tag.outputs.DOCKER_IMAGE_OUTPUT }}"

      # Step 9: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 10: Log in to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PASSWORD }}

      # Step 11: Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Step 12: Set up Docker Buildx for building images
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      # Step 13: Build and push Docker images to registries with caching
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_IMAGE_ENV }}
            ghcr.io/${{ github.repository_owner }}/${{ env.GHCR_IMAGE }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_ENV }}-buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE_ENV }}-buildcache,mode=max

      # Step 14: Save the built Docker image as a tar file (conditional)
      - name: Save Docker image as tar
        if: env.DOWNLOAD_IMAGE == 'true'
        run: |
          docker pull ${{ env.DOCKER_IMAGE_ENV }}
          docker save ${{ env.DOCKER_IMAGE_ENV }} -o docker-image.tar

      # Step 15: Upload the Docker image tar as an artifact (conditional)
      - name: Upload Docker image artifact
        if: env.DOWNLOAD_IMAGE == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: docker-image.tar

  update-deployment:
    runs-on: ubuntu-latest
    needs: docker-build-push
    env:
      REPO_NAME: dockerpoc-1
      DOCKER_IMAGE: ${{ needs.docker-build-push.outputs.docker_image }}
    steps:

      - name: Debug outputs
        run: |
          echo "All outputs from docker-build-push:"
          echo "${{ toJSON(needs.docker-build-push.outputs) }}"
          echo "DOCKER_IMAGE output: ${{ needs.docker-build-push.outputs.docker_image }}"
          echo "DOCKER_IMAGE from env: ${DOCKER_IMAGE}"

      # Step 16: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 17: Update the Deployment YAML file with the new image tag
      - name: Update Deployment YAML
        run: |
          echo ${DOCKER_IMAGE}
          sed -i'' -e "s|image:.*|image: ${DOCKER_IMAGE}|g" K8s_Yaml/App/Deployment.yaml
          cat K8s_Yaml/App/Deployment.yaml

      # Step 18: Commit and push the updated Deployment YAML file to the repository
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add K8s_Yaml/App/Deployment.yaml
          git commit -m "Updated Deployment image to $DOCKER_IMAGE"
          git push origin ${{ github.ref_name }}