name: Build and Deploy

on:
  push:
    branches:
      - learning/github-action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      USER: vishal210893
      REPO_NAME: dockerpoc-1
      DOWNLOAD_IMAGE: false  # Set to 'true' to enable image download steps

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache the local Maven repository to speed up builds
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project using Maven
      - name: Maven build
        run: mvn -q install

      # Step 4.1: Upload the built JAR as an artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/dockerpoc-1-spring-boot.jar

      # Step 5: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Log in to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PASSWORD }}

      # Step 7: Set the Docker image tag
      - name: Set image tag
        run: |
          echo "DOCKER_IMAGE=${USER}/${REPO_NAME}:$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
          echo "GHCR_IMAGE=${REPO_NAME}:$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      # Step 8: Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Step 9: Set up Docker Buildx for building images
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      # Step 10: Build and push Docker images to registries with caching
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_IMAGE }}
            ghcr.io/${{ github.repository_owner }}/${{ env.GHCR_IMAGE }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}-buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}-buildcache,mode=max

      # Step 11: Save the built Docker image as a tar file (conditional)
      - name: Save Docker image as tar
        if: env.DOWNLOAD_IMAGE == 'true'
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}
          docker save ${{ env.DOCKER_IMAGE }} -o docker-image.tar

      # Step 12: Upload the Docker image tar as an artifact (conditional)
      - name: Upload Docker image artifact
        if: env.DOWNLOAD_IMAGE == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: docker-image.tar

      # Step 13: Update the Deployment YAML file with the new image tag
      - name: Update Deployment YAML
        run: |
          sed -i'' -e "s|image: ${USER}/${REPO_NAME}:.*|image: ${DOCKER_IMAGE}|g" K8s_Yaml/App/Deployment.yaml
          cat K8s_Yaml/App/Deployment.yaml

      # Step 14: Commit and push the updated Deployment YAML file to the repository
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add K8s_Yaml/App/Deployment.yaml
          git commit -m "Updated Deployment image to $DOCKER_IMAGE"
          git push origin ${{ github.ref_name }}