name: Build and Deploy

on:
  push:
    branches:
      - learning/github-action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_BASE: vishal210893/dockerpoc-1

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Maven build
      - name: Maven build
        run: mvn -q install

      # Step 4: Set up Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Docker build and push
      - name: Build and push Docker image
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          IMAGE=${DOCKER_IMAGE_BASE}:${TIMESTAMP}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE .
          docker push $IMAGE

      # Step 6: Patch Deployment YAML
      - name: Update Deployment YAML
        run: |
          sed -i'' -e "s|image: ${DOCKER_IMAGE_BASE}:.*|image: ${IMAGE}|g" K8s_Yaml/App/Deployment.yaml
          cat K8s_Yaml/App/Deployment.yaml

      # Step 7: Push changes to GitHub
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add K8s_Yaml/App/Deployment.yaml
          git commit -m "Updated Deployment image to $IMAGE"
          git push origin ${{ github.ref_name }}