name: Release Helm Charts

on:
  push:
    branches:
      - learning/github-action

jobs:
  release:
    permissions:
      contents: write  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GHCR_PASSWORD }}"

      - name: Update README with chart version
        run: |
          chart_version=$(grep '^version:' charts/Helm/Chart.yaml | awk '{print $2}')
          sed -i -E "s/(Current Helm Chart Version: )[0-9]+\.[0-9]+\.[0-9]+/\1${chart_version}/" Readme.md
          sed -i -E "s/(--version )[0-9]+\.[0-9]+\.[0-9]+/\1${chart_version}/" Readme.md
          git add Readme.md
          if git diff --cached --quiet; then
            echo 'README is up to date'
          else
            git commit -m "docs: update Helm chart version to ${chart_version}"
            git push
          fi